import re

def cot_to_list(cot_text):
    """
    Extracts the reasoning steps from a Chain-of-Thought (CoT) and the final answer.
    
    The function parses the text generated by the model, splits the various steps 
    (identified by 'Step N:' or '### Step N'), and extracts the final result 
    located inside the LaTeX '\\boxed{}' block.

    Args:
        cot_text (str): The raw CoT text generated by the model.

    Returns:
        list: A list containing the CoT steps in order. The last element 
              of the list is always the extracted final answer. 
              Returns an empty list if parsing fails.
    """
    cot_text = cot_text.replace(r'\\n', '\n')
    split_pattern = r'(?=^\s*(?:Step \d+|Final Answer)\s*:|### (?:Step \d+|Final Answer))'
    parts = re.split(split_pattern, cot_text, flags=re.MULTILINE)
    steps_list = [part.strip() for part in parts[1:] if part.strip()]

    if not steps_list:
        return []

    final_answer_block = steps_list[-1]
    match = re.search(r'\\boxed\{(.*?)\}', final_answer_block, re.DOTALL)

    if match:
        final_result = re.sub(r'\s+', '', match.group(1))
    else:
        final_result = "ERROR: \\boxed{} not found."

    return steps_list[:-1] + [final_result]